name: pndlm_assessment
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  built_value: ^8.9.4
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  email_validator: ^3.0.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  built_value_generator:
  riverpod_generator:
  custom_lint:
  riverpod_lint:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: figtree
      fonts:
        - asset: assets/fonts/figtree/figtree-latin-400-normal.ttf
        - asset: assets/fonts/figtree/figtree-latin-500-normal.ttf
        - asset: assets/fonts/figtree/figtree-latin-600-normal.ttf
        - asset: assets/fonts/figtree/figtree-latin-700-normal.ttf
